### PR TITLE
Mvc structure

### PR DESCRIPTION
**Pull request by cryocubed**
This change is [Reviewable](https://reviewable.io/reviews/cryocubed/grambot/20)

### CODE REVIEW

**Review by s-cortez — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cryocubed/grambot/20)* status: all files reviewed, 2 unresolved discussions (waiting on @cryocubed and @agracebaca)

___
*[src/main/java/bots/BotManager.java, line 21 at r1](https://reviewable.io/reviews/cryocubed/grambot/20#-LWOe0TG08BzQpjjINi2:-LWOe0TG08BzQpjjINi3:blvhuxd) ([raw file](https://github.com/cryocubed/grambot/blob/6fd668414bf7ba6b2b9b340f93479a6d718ef9b2/src/main/java/bots/BotManager.java#L21)):*
> ```Java
>     throw new RuntimeException("not yet implemented");
>   }
> }
> ```

wait what the difference between this one and the IBotManager
___
*[src/main/java/bots/IBotManager.java, line 17 at r1](https://reviewable.io/reviews/cryocubed/grambot/20#-LWOd6zj2QSvaKJzCcnk:-LWOd6zk4DY3LEhb9KM7:b862u15) ([raw file](https://github.com/cryocubed/grambot/blob/6fd668414bf7ba6b2b9b340f93479a6d718ef9b2/src/main/java/bots/IBotManager.java#L17)):*
> ```Java
>    * Sets the number of followers to be given by bots.
>    */
>   void setUserFollowers(int id, int amount);
> ```

help what id for am confuse

**Review by cryocubed — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cryocubed/grambot/20)* status: all files reviewed, 2 unresolved discussions (waiting on @s-cortez and @agracebaca)

___
*[src/main/java/bots/BotManager.java, line 21 at r1](https://reviewable.io/reviews/cryocubed/grambot/20#-LWOe0TG08BzQpjjINi2:-LWSVQOX0woLjOApq2N9:bhqiatp) ([raw file](https://github.com/cryocubed/grambot/blob/6fd668414bf7ba6b2b9b340f93479a6d718ef9b2/src/main/java/bots/BotManager.java#L21)):*
<details><summary><i>Previously, s-cortez wrote…</i></summary><blockquote>

wait what the difference between this one and the IBotManager
</blockquote></details>

IBotManager defines the interface for how BotManager will work. Essentially it specifies a contract between any part of the program and anything that implements IBotManager. As it exists now, it is the contract between AppController and BotManager. IBotManager specifies that BotManager (or anything other implementing class) will be able to set the number of likes on a post and set the number of followers for a user. It doesn't care how it happens, as long as it can.
___
*[src/main/java/bots/IBotManager.java, line 17 at r1](https://reviewable.io/reviews/cryocubed/grambot/20#-LWOd6zj2QSvaKJzCcnk:-LWSWssqA59FFMD8NnzD:b-15fxxy) ([raw file](https://github.com/cryocubed/grambot/blob/6fd668414bf7ba6b2b9b340f93479a6d718ef9b2/src/main/java/bots/IBotManager.java#L17)):*
<details><summary><i>Previously, s-cortez wrote…</i></summary><blockquote>

help what id for am confuse
</blockquote></details>

Its the ID of the user per the Instagram API.

**Review by agracebaca — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cryocubed/grambot/20)* status: all files reviewed, 2 unresolved discussions (waiting on @s-cortez)

**Review by agracebaca — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cryocubed/grambot/20)* status: all files reviewed, 2 unresolved discussions (waiting on @s-cortez)

**Review by s-cortez — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cryocubed/grambot/20)* status: all files reviewed, 2 unresolved discussions (waiting on @s-cortez)

**Review by s-cortez — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cryocubed/grambot/20)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
